### ISSUE TITLE
Model TS classes need to be held in separate folders inside or outside Migrations folder 

### ISSUE THREAD

**Issue by jp2ld** [kontent-ai/cli#26]
### Motivation

The Kentico model generator (https://github.com/Kentico/kontent-model-generator-js) allows users to generate TS classes to create strictly typed objects to receive data from the Content Delivery APIs (https://github.com/Kentico/kontent-delivery-sdk-js/blob/master/DOCS.md). However there is no way to maintain a subfolder inside or outside the Migrations folder (https://github.com/Kentico/kontent-migrations-boilerplate/tree/master/Migrations) without running into the following errors during execution of the migration CLI:

![image](https://user-images.githubusercontent.com/89982649/132395641-56748940-bffd-4c9f-a012-c6135dae8328.png)

### Proposed solution

Modify the CLI to allow TS files (typically model classes) to be maintained outside or inside the [Migrations folder](https://github.com/Kentico/kontent-migrations-boilerplate/tree/master/Migrations). There should be a way to set the compiler to allow folders with model files during Transpiling. This will allow easier maintenance of code.

**Comment by winklertomas** [comment]
Hi @jp2ld,

I've looked at it and I don't think it's a kontent-cli issue since it's only capable of running JS migrations in the current implementation. It's more a question of setting up the transpilation of TS migrations within the boilerplate. We created the boilerplate just as an example of what migrations you can write and how you can run them. If you have specific requirements, you can customize the boilerplate code. In this case, I think it should be enough to add include in tsconfig.json, see https://www.typescriptlang.org/tsconfig#include. 

Can I just ask why you need models from the Delivery API? Are you missing any data in the management API?

**Comment by winklertomas** [comment]
Hi! 

This issue has gone quiet. 👻 
It’s been a while since the last update here. 

If we missed anything on this issue or if you want to keep it open, please reply here.  

Thanks for being a part of the Kentico community!
